### ISSUE TITLE
Confusing documentation references to AES-128-GCM in MessageEncryptor

### ISSUE THREAD

**Issue by liamwhite** [elixir-plug/plug_crypto#11]
In MessageEncryptor, steps are taken as follows to encode session data: https://github.com/elixir-plug/plug_crypto/blob/f7a1142dc80c4e0f872bd65b1b86e6a9647eca0e/lib/plug/crypto/message_encryptor.ex#L58-L67
1. Generate a 128-bit random key (the CEK) for encrypting the session. (ok)
2. Encrypt the session data with AES-128-GCM using the random key and AAD `"A128GCM"`. (ok)
3. Encrypt the 128-bit random key from step 1 with AES-256-GCM using the 256-bit secret key as the key and the 256-bit signing key as AAD. (!)
4. Base-64 encode the generated token and format it for cookie storage (ok)

This isn't a security issue (I didn't find any issues with this implementation) but it is relevant to me because I am [writing a session decoder](https://github.com/liamwhite/cookie_check/blob/2115fd1/src/lib.rs), and it does not work without understanding that the CEK is encrypted using AES-256-GCM, so I think this should at least be mentioned in the comments in MessageEncryptor (and preferably, would also be mentioned in the module documentation).

**Comment by josevalim** [comment]
Pinging @GriffinMB as he will provide the relevant info. :) Thanks in advance @GriffinMB. :D

**Comment by GriffinMB** [comment]
Hi @liamwhite! 

The CEK is encrypted using a variable key length based on the provided secret, so it may be 128, 192, or 256 bits. I added a note to the comments [here](https://github.com/elixir-plug/plug_crypto/pull/12) to help people who are exploring the codebase, but I think the implementation details[^1] are intended to be opaque to end-users. 

Happy to clarify docs as well if we decide this is something worth surfacing!

[^1]: aside from the fact that content is encrypted using AES-128-GCM

**Comment by liamwhite** [comment]
LGTM, thanks!
