### ISSUE TITLE
Security: Plug.Crypto.sign/3 and Plug.Crypto.encrypt/3 allows to sign empty data with empty secret and salt

### ISSUE THREAD

**Issue by Exadra37** [elixir-plug/plug_crypto#13]
This is unexpected:

```
iex> Plug.Crypto.sign "", "", ""                                
"SFMyNTY.g2gDbQAAAABuBgAWMyflcQFiAAFRgA.QFzpJfv3HeYdNU7fTjjbDhIVjrM9QTOFWWSytnA1v_E"
```

and this too:

```
iex> Plug.Crypto.encrypt "", "", ""
"QTEyOEdDTQ.i9CSgrZX2SkFNiK-20v3kLN-H3qHT2Dgq51fqV7YnXF-uR_shQPqBu0BpDg.9AaepQaobCgRQPL7.bdliPJ-iXyoFRcW_oKgn9HQOL3F4jw.wIX97k9OytAjfxiyIBR94A"
```

In my opinion none of the parameters should allow empty data.

This is also unexpected:

```
iex> Plug.Crypto.sign "", "", nil
"SFMyNTY.g2gDZAADbmlsbgYAgcUs5XEBYgABUYA.iVkYeAUWgvwfeEv5ZQjFhZgI7SobdUNMkwE2g8-OUZs"
```

and this too:

```
iex> Plug.Crypto.encrypt "", "", nil
"QTEyOEdDTQ.0qxI-t6Dfnmh_VIQwOLEDKj4xtjfjk-c0AaJzgKnYo5X8E8TLrdhQXPmD1s.XlTlQSSWdZyLRvkd.pfCwRXKFP6MGe8SyEfXJBNkQMV1EhI4.d53JPqhz8r3r9rtRD-tKWw"
```
I also think that here `nil` data should raise an error, as it raises when used as a secret or salt.

**Comment by josevalim** [comment]
Nil data is definitely fine, as we allow any term, but we should definitely enforce non nil secret key base and salts.

**Comment by Exadra37** [comment]
> Nil data is definitely fine,

I don't see why, but I am curious to know an example of a good use case to encrypt or sign empty data?

I discover this issue because I am hardening a known OAuth package and during it's development I end-up to sign tokens in this way with `Phoenix.Token` that uses this library under the hood.

Just as a side note I am now curious to see how this will be fixed, because I was trying to write a  [guard clause](https://elixirforum.com/t/its-possible-to-write-a-custom-guard-to-check-for-a-blank-string/31199) to detect empty values, but with no avail, because it seems Erlang doesn't allow to do it.
