### ISSUE TITLE
Quick question about the handling of derived key size check

### ISSUE THREAD

**Issue by srfsh** [elixir-plug/plug_crypto#28]
Hi,

I'd like to ask a quick question about how [the derived key size check](https://github.com/elixir-plug/plug_crypto/blob/master/lib/plug/crypto/key_generator.ex#L47) is handled.

I am not a cryptographer (that's why I ask), but I think [it doesn't conform to the standard](https://datatracker.ietf.org/doc/html/rfc8018#section-5.2).  The standard reads:

> [...]
> hLen: length in octets of pseudorandom function output, a positive integer
> [....]
> dkLen: intended length in octets of the derived  key, a positive integer, at most  (2^32 - 1) * hLen
> [...]
> If dkLen > (2^32 - 1) * hLen, output  "derived key too long" and stop.

If it were to conform to the standard, it would do:
```
length > (max = @max_length * :crypto.hash_info(digest).size) ->
	raise ArgumentError, "length must be less than or equal to #{max} for #{digest}"
```
I assume.

Please tell me what you think!  ^^

Cheers,
srfsh

**Comment by josevalim** [comment]
Thanks! My understanding is that it doesn't matter. `@max_length` is already `4_294_967_295`, which would be 4GB. Your version would allow it go beyond that but I don't see anyone using such a high value in practice. We could reduce it by 3 orders of magnitude and it would still likely be unusable in practice. In other words, we are effectively a subset of the allowed values in the spec and I would say that's fine. :)

**Comment by srfsh** [comment]
> Thanks! My understanding is that it doesn't matter. `@max_length` is already `4_294_967_295`, which would be 4GB. Your version would allow it go beyond that but I don't see anyone using such a high value in practice. We could reduce it by 3 orders of magnitude and it would still likely be unusable in practice. In other words, we are effectively a subset of the allowed values in the spec and I would say that's fine. :)

As I am not a cryptographer, I'll take your word for it.  Thanks for the explanation!
