### ISSUE TITLE
KeyGenerator provides 512 bit long key, not 256 bit.

### ISSUE THREAD

**Issue by pled76** [elixir-plug/plug_crypto#38]
The result is encrypt and decrypt not working raising errors of not matching functions because of guards bit_size(256).

**Comment by grzuy** [comment]
Related thread https://github.com/elixir-plug/plug_crypto/commit/ae684cde84f6e3035dad74d69868d4573e689e3b#r130774062

**Comment by FeeJai** [comment]
Ping?

**Comment by josevalim** [comment]
Smaller key lengths are no longer supported in the latest version of this library. You have to remove the setting accordingly. Please see the linked issue in Plug too.
