### ISSUE TITLE
Add versioning to the signatures

### ISSUE THREAD

**Issue by hauleth** [elixir-plug/plug_crypto#4]
This could work in similar way to the [PASETO](https://paseto.io) where we have prefix:

- `v1.public` for `Plug.Crypto.MessageVerifier` messages
- `v1.local` for `Plug.Crypto.MessageEncryptor` messages

This would allow to change used algorithms in future if needed without introducing breaking changes.

**Comment by josevalim** [comment]
We do add a constant string at the beginning, so in case in we have to change implementation, we can do so without breaking changes. The string is not currently versioned, but we can do so in the future if we ever have to change it.
