### ISSUE TITLE
Any plans to use the new crypto API introduced in OTP 22?

### ISSUE THREAD

**Issue by alco** [elixir-plug/plug_crypto#5]
From http://erlang.org/doc/apps/crypto/new_api.html:

> The old functions - not recommended for new programs - are:
>
>    - block_encrypt/3
>    - block_encrypt/4
>    - block_decrypt/3
>    - block_decrypt/4

> The new functions for encrypting or decrypting one single binary are:
>
>    - crypto_one_time/4
>    - crypto_one_time/5
>    - crypto_one_time_aead/6
>    - crypto_one_time_aead/7

The old API hasn't been deprecated, but the reference docs show a big red `Don't` box for old functions, e.g. http://erlang.org/doc/man/crypto.html#block_decrypt-3.

**Comment by josevalim** [comment]
Hard to do so without breaking old versions but we could keep them behind a conditional block. PRs are welcome!
